/*
 * This file is generated by jOOQ.
 */
package me.myblog.framework.domain.jooq.tables.pojos;


import java.time.LocalDateTime;

import me.myblog.framework.domain.jooq.tables.interfaces.IArticle;


/**
 * 文章表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Article implements IArticle {

    private static final long serialVersionUID = 1L;

    private Long id;
    private String title;
    private String content;
    private String summary;
    private Long categoryId;
    private String thumbnail;
    private String isTop;
    private String status;
    private Long viewCount;
    private String isComment;
    private Long createBy;
    private LocalDateTime createTime;
    private Long updateBy;
    private LocalDateTime updateTime;

    public Article() {}

    public Article(IArticle value) {
        this.id = value.getId();
        this.title = value.getTitle();
        this.content = value.getContent();
        this.summary = value.getSummary();
        this.categoryId = value.getCategoryId();
        this.thumbnail = value.getThumbnail();
        this.isTop = value.getIsTop();
        this.status = value.getStatus();
        this.viewCount = value.getViewCount();
        this.isComment = value.getIsComment();
        this.createBy = value.getCreateBy();
        this.createTime = value.getCreateTime();
        this.updateBy = value.getUpdateBy();
        this.updateTime = value.getUpdateTime();
    }

    public Article(
        Long id,
        String title,
        String content,
        String summary,
        Long categoryId,
        String thumbnail,
        String isTop,
        String status,
        Long viewCount,
        String isComment,
        Long createBy,
        LocalDateTime createTime,
        Long updateBy,
        LocalDateTime updateTime
    ) {
        this.id = id;
        this.title = title;
        this.content = content;
        this.summary = summary;
        this.categoryId = categoryId;
        this.thumbnail = thumbnail;
        this.isTop = isTop;
        this.status = status;
        this.viewCount = viewCount;
        this.isComment = isComment;
        this.createBy = createBy;
        this.createTime = createTime;
        this.updateBy = updateBy;
        this.updateTime = updateTime;
    }

    /**
     * Getter for <code>myblog.article.id</code>.
     */
    @Override
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>myblog.article.id</code>.
     */
    @Override
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>myblog.article.title</code>. 标题
     */
    @Override
    public String getTitle() {
        return this.title;
    }

    /**
     * Setter for <code>myblog.article.title</code>. 标题
     */
    @Override
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * Getter for <code>myblog.article.content</code>. 文章内容
     */
    @Override
    public String getContent() {
        return this.content;
    }

    /**
     * Setter for <code>myblog.article.content</code>. 文章内容
     */
    @Override
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * Getter for <code>myblog.article.summary</code>. 文章摘要
     */
    @Override
    public String getSummary() {
        return this.summary;
    }

    /**
     * Setter for <code>myblog.article.summary</code>. 文章摘要
     */
    @Override
    public void setSummary(String summary) {
        this.summary = summary;
    }

    /**
     * Getter for <code>myblog.article.category_id</code>. 所属分类id
     */
    @Override
    public Long getCategoryId() {
        return this.categoryId;
    }

    /**
     * Setter for <code>myblog.article.category_id</code>. 所属分类id
     */
    @Override
    public void setCategoryId(Long categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * Getter for <code>myblog.article.thumbnail</code>. 缩略图
     */
    @Override
    public String getThumbnail() {
        return this.thumbnail;
    }

    /**
     * Setter for <code>myblog.article.thumbnail</code>. 缩略图
     */
    @Override
    public void setThumbnail(String thumbnail) {
        this.thumbnail = thumbnail;
    }

    /**
     * Getter for <code>myblog.article.is_top</code>. 是否置顶（0否，1是）
     */
    @Override
    public String getIsTop() {
        return this.isTop;
    }

    /**
     * Setter for <code>myblog.article.is_top</code>. 是否置顶（0否，1是）
     */
    @Override
    public void setIsTop(String isTop) {
        this.isTop = isTop;
    }

    /**
     * Getter for <code>myblog.article.status</code>. 状态（0已发布，1草稿）
     */
    @Override
    public String getStatus() {
        return this.status;
    }

    /**
     * Setter for <code>myblog.article.status</code>. 状态（0已发布，1草稿）
     */
    @Override
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * Getter for <code>myblog.article.view_count</code>. 访问量
     */
    @Override
    public Long getViewCount() {
        return this.viewCount;
    }

    /**
     * Setter for <code>myblog.article.view_count</code>. 访问量
     */
    @Override
    public void setViewCount(Long viewCount) {
        this.viewCount = viewCount;
    }

    /**
     * Getter for <code>myblog.article.is_comment</code>. 是否允许评论（1是，0否）
     */
    @Override
    public String getIsComment() {
        return this.isComment;
    }

    /**
     * Setter for <code>myblog.article.is_comment</code>. 是否允许评论（1是，0否）
     */
    @Override
    public void setIsComment(String isComment) {
        this.isComment = isComment;
    }

    /**
     * Getter for <code>myblog.article.create_by</code>.
     */
    @Override
    public Long getCreateBy() {
        return this.createBy;
    }

    /**
     * Setter for <code>myblog.article.create_by</code>.
     */
    @Override
    public void setCreateBy(Long createBy) {
        this.createBy = createBy;
    }

    /**
     * Getter for <code>myblog.article.create_time</code>.
     */
    @Override
    public LocalDateTime getCreateTime() {
        return this.createTime;
    }

    /**
     * Setter for <code>myblog.article.create_time</code>.
     */
    @Override
    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    /**
     * Getter for <code>myblog.article.update_by</code>.
     */
    @Override
    public Long getUpdateBy() {
        return this.updateBy;
    }

    /**
     * Setter for <code>myblog.article.update_by</code>.
     */
    @Override
    public void setUpdateBy(Long updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * Getter for <code>myblog.article.update_time</code>.
     */
    @Override
    public LocalDateTime getUpdateTime() {
        return this.updateTime;
    }

    /**
     * Setter for <code>myblog.article.update_time</code>.
     */
    @Override
    public void setUpdateTime(LocalDateTime updateTime) {
        this.updateTime = updateTime;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Article other = (Article) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.title == null) {
            if (other.title != null)
                return false;
        }
        else if (!this.title.equals(other.title))
            return false;
        if (this.content == null) {
            if (other.content != null)
                return false;
        }
        else if (!this.content.equals(other.content))
            return false;
        if (this.summary == null) {
            if (other.summary != null)
                return false;
        }
        else if (!this.summary.equals(other.summary))
            return false;
        if (this.categoryId == null) {
            if (other.categoryId != null)
                return false;
        }
        else if (!this.categoryId.equals(other.categoryId))
            return false;
        if (this.thumbnail == null) {
            if (other.thumbnail != null)
                return false;
        }
        else if (!this.thumbnail.equals(other.thumbnail))
            return false;
        if (this.isTop == null) {
            if (other.isTop != null)
                return false;
        }
        else if (!this.isTop.equals(other.isTop))
            return false;
        if (this.status == null) {
            if (other.status != null)
                return false;
        }
        else if (!this.status.equals(other.status))
            return false;
        if (this.viewCount == null) {
            if (other.viewCount != null)
                return false;
        }
        else if (!this.viewCount.equals(other.viewCount))
            return false;
        if (this.isComment == null) {
            if (other.isComment != null)
                return false;
        }
        else if (!this.isComment.equals(other.isComment))
            return false;
        if (this.createBy == null) {
            if (other.createBy != null)
                return false;
        }
        else if (!this.createBy.equals(other.createBy))
            return false;
        if (this.createTime == null) {
            if (other.createTime != null)
                return false;
        }
        else if (!this.createTime.equals(other.createTime))
            return false;
        if (this.updateBy == null) {
            if (other.updateBy != null)
                return false;
        }
        else if (!this.updateBy.equals(other.updateBy))
            return false;
        if (this.updateTime == null) {
            if (other.updateTime != null)
                return false;
        }
        else if (!this.updateTime.equals(other.updateTime))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.title == null) ? 0 : this.title.hashCode());
        result = prime * result + ((this.content == null) ? 0 : this.content.hashCode());
        result = prime * result + ((this.summary == null) ? 0 : this.summary.hashCode());
        result = prime * result + ((this.categoryId == null) ? 0 : this.categoryId.hashCode());
        result = prime * result + ((this.thumbnail == null) ? 0 : this.thumbnail.hashCode());
        result = prime * result + ((this.isTop == null) ? 0 : this.isTop.hashCode());
        result = prime * result + ((this.status == null) ? 0 : this.status.hashCode());
        result = prime * result + ((this.viewCount == null) ? 0 : this.viewCount.hashCode());
        result = prime * result + ((this.isComment == null) ? 0 : this.isComment.hashCode());
        result = prime * result + ((this.createBy == null) ? 0 : this.createBy.hashCode());
        result = prime * result + ((this.createTime == null) ? 0 : this.createTime.hashCode());
        result = prime * result + ((this.updateBy == null) ? 0 : this.updateBy.hashCode());
        result = prime * result + ((this.updateTime == null) ? 0 : this.updateTime.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Article (");

        sb.append(id);
        sb.append(", ").append(title);
        sb.append(", ").append(content);
        sb.append(", ").append(summary);
        sb.append(", ").append(categoryId);
        sb.append(", ").append(thumbnail);
        sb.append(", ").append(isTop);
        sb.append(", ").append(status);
        sb.append(", ").append(viewCount);
        sb.append(", ").append(isComment);
        sb.append(", ").append(createBy);
        sb.append(", ").append(createTime);
        sb.append(", ").append(updateBy);
        sb.append(", ").append(updateTime);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IArticle from) {
        setId(from.getId());
        setTitle(from.getTitle());
        setContent(from.getContent());
        setSummary(from.getSummary());
        setCategoryId(from.getCategoryId());
        setThumbnail(from.getThumbnail());
        setIsTop(from.getIsTop());
        setStatus(from.getStatus());
        setViewCount(from.getViewCount());
        setIsComment(from.getIsComment());
        setCreateBy(from.getCreateBy());
        setCreateTime(from.getCreateTime());
        setUpdateBy(from.getUpdateBy());
        setUpdateTime(from.getUpdateTime());
    }

    @Override
    public <E extends IArticle> E into(E into) {
        into.from(this);
        return into;
    }
}
