/*
 * This file is generated by jOOQ.
 */
package me.myblog.framework.domain.jooq.tables.pojos;


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Table;

import me.myblog.framework.domain.jooq.tables.interfaces.IArticleTag;


/**
 * 文章标签关联表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
@Entity
@Table(
    name = "article_tag",
    schema = "myblog"
)
public class ArticleTag implements IArticleTag {

    private static final long serialVersionUID = 1L;

    private final Long articleId;
    private final Long tagId;

    public ArticleTag(IArticleTag value) {
        this.articleId = value.getArticleId();
        this.tagId = value.getTagId();
    }

    public ArticleTag(
        Long articleId,
        Long tagId
    ) {
        this.articleId = articleId;
        this.tagId = tagId;
    }

    /**
     * Getter for <code>myblog.article_tag.article_id</code>. 文章id
     */
    @Column(name = "article_id")
    @Override
    public Long getArticleId() {
        return this.articleId;
    }

    /**
     * Getter for <code>myblog.article_tag.tag_id</code>. 标签id
     */
    @Column(name = "tag_id")
    @Override
    public Long getTagId() {
        return this.tagId;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final ArticleTag other = (ArticleTag) obj;
        if (this.articleId == null) {
            if (other.articleId != null)
                return false;
        }
        else if (!this.articleId.equals(other.articleId))
            return false;
        if (this.tagId == null) {
            if (other.tagId != null)
                return false;
        }
        else if (!this.tagId.equals(other.tagId))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.articleId == null) ? 0 : this.articleId.hashCode());
        result = prime * result + ((this.tagId == null) ? 0 : this.tagId.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ArticleTag (");

        sb.append(articleId);
        sb.append(", ").append(tagId);

        sb.append(")");
        return sb.toString();
    }
}
