/*
 * This file is generated by jOOQ.
 */
package me.myblog.framework.domain.jooq.tables.pojos;


import java.time.LocalDateTime;

import me.myblog.framework.domain.jooq.tables.interfaces.IRole;


/**
 * 角色信息表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Role implements IRole {

    private static final long serialVersionUID = 1L;

    private Long id;
    private String roleName;
    private String roleKey;
    private Integer roleSort;
    private String status;
    private Long createBy;
    private LocalDateTime createTime;
    private Long updateBy;
    private LocalDateTime updateTime;
    private String remark;

    public Role() {}

    public Role(IRole value) {
        this.id = value.getId();
        this.roleName = value.getRoleName();
        this.roleKey = value.getRoleKey();
        this.roleSort = value.getRoleSort();
        this.status = value.getStatus();
        this.createBy = value.getCreateBy();
        this.createTime = value.getCreateTime();
        this.updateBy = value.getUpdateBy();
        this.updateTime = value.getUpdateTime();
        this.remark = value.getRemark();
    }

    public Role(
        Long id,
        String roleName,
        String roleKey,
        Integer roleSort,
        String status,
        Long createBy,
        LocalDateTime createTime,
        Long updateBy,
        LocalDateTime updateTime,
        String remark
    ) {
        this.id = id;
        this.roleName = roleName;
        this.roleKey = roleKey;
        this.roleSort = roleSort;
        this.status = status;
        this.createBy = createBy;
        this.createTime = createTime;
        this.updateBy = updateBy;
        this.updateTime = updateTime;
        this.remark = remark;
    }

    /**
     * Getter for <code>myblog.role.id</code>. 角色ID
     */
    @Override
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>myblog.role.id</code>. 角色ID
     */
    @Override
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>myblog.role.role_name</code>. 角色名称
     */
    @Override
    public String getRoleName() {
        return this.roleName;
    }

    /**
     * Setter for <code>myblog.role.role_name</code>. 角色名称
     */
    @Override
    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

    /**
     * Getter for <code>myblog.role.role_key</code>. 角色权限字符串
     */
    @Override
    public String getRoleKey() {
        return this.roleKey;
    }

    /**
     * Setter for <code>myblog.role.role_key</code>. 角色权限字符串
     */
    @Override
    public void setRoleKey(String roleKey) {
        this.roleKey = roleKey;
    }

    /**
     * Getter for <code>myblog.role.role_sort</code>. 显示顺序
     */
    @Override
    public Integer getRoleSort() {
        return this.roleSort;
    }

    /**
     * Setter for <code>myblog.role.role_sort</code>. 显示顺序
     */
    @Override
    public void setRoleSort(Integer roleSort) {
        this.roleSort = roleSort;
    }

    /**
     * Getter for <code>myblog.role.status</code>. 角色状态（0正常，1停用）
     */
    @Override
    public String getStatus() {
        return this.status;
    }

    /**
     * Setter for <code>myblog.role.status</code>. 角色状态（0正常，1停用）
     */
    @Override
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * Getter for <code>myblog.role.create_by</code>. 创建者
     */
    @Override
    public Long getCreateBy() {
        return this.createBy;
    }

    /**
     * Setter for <code>myblog.role.create_by</code>. 创建者
     */
    @Override
    public void setCreateBy(Long createBy) {
        this.createBy = createBy;
    }

    /**
     * Getter for <code>myblog.role.create_time</code>. 创建时间
     */
    @Override
    public LocalDateTime getCreateTime() {
        return this.createTime;
    }

    /**
     * Setter for <code>myblog.role.create_time</code>. 创建时间
     */
    @Override
    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    /**
     * Getter for <code>myblog.role.update_by</code>. 更新者
     */
    @Override
    public Long getUpdateBy() {
        return this.updateBy;
    }

    /**
     * Setter for <code>myblog.role.update_by</code>. 更新者
     */
    @Override
    public void setUpdateBy(Long updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * Getter for <code>myblog.role.update_time</code>. 更新时间
     */
    @Override
    public LocalDateTime getUpdateTime() {
        return this.updateTime;
    }

    /**
     * Setter for <code>myblog.role.update_time</code>. 更新时间
     */
    @Override
    public void setUpdateTime(LocalDateTime updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * Getter for <code>myblog.role.remark</code>. 备注
     */
    @Override
    public String getRemark() {
        return this.remark;
    }

    /**
     * Setter for <code>myblog.role.remark</code>. 备注
     */
    @Override
    public void setRemark(String remark) {
        this.remark = remark;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Role other = (Role) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.roleName == null) {
            if (other.roleName != null)
                return false;
        }
        else if (!this.roleName.equals(other.roleName))
            return false;
        if (this.roleKey == null) {
            if (other.roleKey != null)
                return false;
        }
        else if (!this.roleKey.equals(other.roleKey))
            return false;
        if (this.roleSort == null) {
            if (other.roleSort != null)
                return false;
        }
        else if (!this.roleSort.equals(other.roleSort))
            return false;
        if (this.status == null) {
            if (other.status != null)
                return false;
        }
        else if (!this.status.equals(other.status))
            return false;
        if (this.createBy == null) {
            if (other.createBy != null)
                return false;
        }
        else if (!this.createBy.equals(other.createBy))
            return false;
        if (this.createTime == null) {
            if (other.createTime != null)
                return false;
        }
        else if (!this.createTime.equals(other.createTime))
            return false;
        if (this.updateBy == null) {
            if (other.updateBy != null)
                return false;
        }
        else if (!this.updateBy.equals(other.updateBy))
            return false;
        if (this.updateTime == null) {
            if (other.updateTime != null)
                return false;
        }
        else if (!this.updateTime.equals(other.updateTime))
            return false;
        if (this.remark == null) {
            if (other.remark != null)
                return false;
        }
        else if (!this.remark.equals(other.remark))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.roleName == null) ? 0 : this.roleName.hashCode());
        result = prime * result + ((this.roleKey == null) ? 0 : this.roleKey.hashCode());
        result = prime * result + ((this.roleSort == null) ? 0 : this.roleSort.hashCode());
        result = prime * result + ((this.status == null) ? 0 : this.status.hashCode());
        result = prime * result + ((this.createBy == null) ? 0 : this.createBy.hashCode());
        result = prime * result + ((this.createTime == null) ? 0 : this.createTime.hashCode());
        result = prime * result + ((this.updateBy == null) ? 0 : this.updateBy.hashCode());
        result = prime * result + ((this.updateTime == null) ? 0 : this.updateTime.hashCode());
        result = prime * result + ((this.remark == null) ? 0 : this.remark.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Role (");

        sb.append(id);
        sb.append(", ").append(roleName);
        sb.append(", ").append(roleKey);
        sb.append(", ").append(roleSort);
        sb.append(", ").append(status);
        sb.append(", ").append(createBy);
        sb.append(", ").append(createTime);
        sb.append(", ").append(updateBy);
        sb.append(", ").append(updateTime);
        sb.append(", ").append(remark);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IRole from) {
        setId(from.getId());
        setRoleName(from.getRoleName());
        setRoleKey(from.getRoleKey());
        setRoleSort(from.getRoleSort());
        setStatus(from.getStatus());
        setCreateBy(from.getCreateBy());
        setCreateTime(from.getCreateTime());
        setUpdateBy(from.getUpdateBy());
        setUpdateTime(from.getUpdateTime());
        setRemark(from.getRemark());
    }

    @Override
    public <E extends IRole> E into(E into) {
        into.from(this);
        return into;
    }
}
