/*
 * This file is generated by jOOQ.
 */
package me.myblog.framework.domain.jooq.tables.pojos;


import java.time.LocalDateTime;

import me.myblog.framework.domain.jooq.tables.interfaces.ITag;


/**
 * 标签
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tag implements ITag {

    private static final long serialVersionUID = 1L;

    private Long id;
    private String name;
    private Long createBy;
    private LocalDateTime createTime;
    private Long updateBy;
    private LocalDateTime updateTime;
    private String remark;

    public Tag() {}

    public Tag(ITag value) {
        this.id = value.getId();
        this.name = value.getName();
        this.createBy = value.getCreateBy();
        this.createTime = value.getCreateTime();
        this.updateBy = value.getUpdateBy();
        this.updateTime = value.getUpdateTime();
        this.remark = value.getRemark();
    }

    public Tag(
        Long id,
        String name,
        Long createBy,
        LocalDateTime createTime,
        Long updateBy,
        LocalDateTime updateTime,
        String remark
    ) {
        this.id = id;
        this.name = name;
        this.createBy = createBy;
        this.createTime = createTime;
        this.updateBy = updateBy;
        this.updateTime = updateTime;
        this.remark = remark;
    }

    /**
     * Getter for <code>myblog.tag.id</code>.
     */
    @Override
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>myblog.tag.id</code>.
     */
    @Override
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>myblog.tag.name</code>. 标签名
     */
    @Override
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>myblog.tag.name</code>. 标签名
     */
    @Override
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for <code>myblog.tag.create_by</code>.
     */
    @Override
    public Long getCreateBy() {
        return this.createBy;
    }

    /**
     * Setter for <code>myblog.tag.create_by</code>.
     */
    @Override
    public void setCreateBy(Long createBy) {
        this.createBy = createBy;
    }

    /**
     * Getter for <code>myblog.tag.create_time</code>.
     */
    @Override
    public LocalDateTime getCreateTime() {
        return this.createTime;
    }

    /**
     * Setter for <code>myblog.tag.create_time</code>.
     */
    @Override
    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    /**
     * Getter for <code>myblog.tag.update_by</code>.
     */
    @Override
    public Long getUpdateBy() {
        return this.updateBy;
    }

    /**
     * Setter for <code>myblog.tag.update_by</code>.
     */
    @Override
    public void setUpdateBy(Long updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * Getter for <code>myblog.tag.update_time</code>.
     */
    @Override
    public LocalDateTime getUpdateTime() {
        return this.updateTime;
    }

    /**
     * Setter for <code>myblog.tag.update_time</code>.
     */
    @Override
    public void setUpdateTime(LocalDateTime updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * Getter for <code>myblog.tag.remark</code>. 备注
     */
    @Override
    public String getRemark() {
        return this.remark;
    }

    /**
     * Setter for <code>myblog.tag.remark</code>. 备注
     */
    @Override
    public void setRemark(String remark) {
        this.remark = remark;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Tag other = (Tag) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.name == null) {
            if (other.name != null)
                return false;
        }
        else if (!this.name.equals(other.name))
            return false;
        if (this.createBy == null) {
            if (other.createBy != null)
                return false;
        }
        else if (!this.createBy.equals(other.createBy))
            return false;
        if (this.createTime == null) {
            if (other.createTime != null)
                return false;
        }
        else if (!this.createTime.equals(other.createTime))
            return false;
        if (this.updateBy == null) {
            if (other.updateBy != null)
                return false;
        }
        else if (!this.updateBy.equals(other.updateBy))
            return false;
        if (this.updateTime == null) {
            if (other.updateTime != null)
                return false;
        }
        else if (!this.updateTime.equals(other.updateTime))
            return false;
        if (this.remark == null) {
            if (other.remark != null)
                return false;
        }
        else if (!this.remark.equals(other.remark))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        result = prime * result + ((this.createBy == null) ? 0 : this.createBy.hashCode());
        result = prime * result + ((this.createTime == null) ? 0 : this.createTime.hashCode());
        result = prime * result + ((this.updateBy == null) ? 0 : this.updateBy.hashCode());
        result = prime * result + ((this.updateTime == null) ? 0 : this.updateTime.hashCode());
        result = prime * result + ((this.remark == null) ? 0 : this.remark.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Tag (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(createBy);
        sb.append(", ").append(createTime);
        sb.append(", ").append(updateBy);
        sb.append(", ").append(updateTime);
        sb.append(", ").append(remark);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(ITag from) {
        setId(from.getId());
        setName(from.getName());
        setCreateBy(from.getCreateBy());
        setCreateTime(from.getCreateTime());
        setUpdateBy(from.getUpdateBy());
        setUpdateTime(from.getUpdateTime());
        setRemark(from.getRemark());
    }

    @Override
    public <E extends ITag> E into(E into) {
        into.from(this);
        return into;
    }
}
