/*
 * This file is generated by jOOQ.
 */
package me.myblog.framework.domain.jooq.tables.pojos;


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Table;
import jakarta.validation.constraints.NotNull;

import me.myblog.framework.domain.jooq.tables.interfaces.IUserRole;


/**
 * 用户和角色关联表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
@Entity
@Table(
    name = "user_role",
    schema = "myblog"
)
public class UserRole implements IUserRole {

    private static final long serialVersionUID = 1L;

    private final Long userId;
    private final Long roleId;

    public UserRole(IUserRole value) {
        this.userId = value.getUserId();
        this.roleId = value.getRoleId();
    }

    public UserRole(
        Long userId,
        Long roleId
    ) {
        this.userId = userId;
        this.roleId = roleId;
    }

    /**
     * Getter for <code>myblog.user_role.user_id</code>. 用户ID
     */
    @Column(name = "user_id", nullable = false)
    @NotNull
    @Override
    public Long getUserId() {
        return this.userId;
    }

    /**
     * Getter for <code>myblog.user_role.role_id</code>. 角色ID
     */
    @Column(name = "role_id", nullable = false)
    @NotNull
    @Override
    public Long getRoleId() {
        return this.roleId;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final UserRole other = (UserRole) obj;
        if (this.userId == null) {
            if (other.userId != null)
                return false;
        }
        else if (!this.userId.equals(other.userId))
            return false;
        if (this.roleId == null) {
            if (other.roleId != null)
                return false;
        }
        else if (!this.roleId.equals(other.roleId))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.userId == null) ? 0 : this.userId.hashCode());
        result = prime * result + ((this.roleId == null) ? 0 : this.roleId.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UserRole (");

        sb.append(userId);
        sb.append(", ").append(roleId);

        sb.append(")");
        return sb.toString();
    }
}
