/*
 * This file is generated by jOOQ.
 */
package me.myblog.framework.domain.jooq.tables.pojos;


import me.myblog.framework.domain.jooq.tables.interfaces.IUserRole;


/**
 * 用户和角色关联表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UserRole implements IUserRole {

    private static final long serialVersionUID = 1L;

    private Long userId;
    private Long roleId;

    public UserRole() {}

    public UserRole(IUserRole value) {
        this.userId = value.getUserId();
        this.roleId = value.getRoleId();
    }

    public UserRole(
        Long userId,
        Long roleId
    ) {
        this.userId = userId;
        this.roleId = roleId;
    }

    /**
     * Getter for <code>myblog.user_role.user_id</code>. 用户ID
     */
    @Override
    public Long getUserId() {
        return this.userId;
    }

    /**
     * Setter for <code>myblog.user_role.user_id</code>. 用户ID
     */
    @Override
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * Getter for <code>myblog.user_role.role_id</code>. 角色ID
     */
    @Override
    public Long getRoleId() {
        return this.roleId;
    }

    /**
     * Setter for <code>myblog.user_role.role_id</code>. 角色ID
     */
    @Override
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final UserRole other = (UserRole) obj;
        if (this.userId == null) {
            if (other.userId != null)
                return false;
        }
        else if (!this.userId.equals(other.userId))
            return false;
        if (this.roleId == null) {
            if (other.roleId != null)
                return false;
        }
        else if (!this.roleId.equals(other.roleId))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.userId == null) ? 0 : this.userId.hashCode());
        result = prime * result + ((this.roleId == null) ? 0 : this.roleId.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UserRole (");

        sb.append(userId);
        sb.append(", ").append(roleId);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IUserRole from) {
        setUserId(from.getUserId());
        setRoleId(from.getRoleId());
    }

    @Override
    public <E extends IUserRole> E into(E into) {
        into.from(this);
        return into;
    }
}
