server:
  port: 7777
spring:
  threads:
    virtual:
      enabled: true
  servlet:
    multipart:
      max-request-size: 5MB
      max-file-size: 2MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/myblog
    username: root
    password: root
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
oss:
  endpoint: http://localhost:9000
  bucketName: myblog
  accessKey: minioadmin
  secretKey: minioadmin