/*
 * This file is generated by jOOQ.
 */
package me.myblog.framework.domain.jooq;


import java.util.Arrays;
import java.util.List;

import me.myblog.framework.domain.jooq.tables.Article;
import me.myblog.framework.domain.jooq.tables.ArticleTag;
import me.myblog.framework.domain.jooq.tables.Category;
import me.myblog.framework.domain.jooq.tables.Comment;
import me.myblog.framework.domain.jooq.tables.Link;
import me.myblog.framework.domain.jooq.tables.Menu;
import me.myblog.framework.domain.jooq.tables.Role;
import me.myblog.framework.domain.jooq.tables.Tag;
import me.myblog.framework.domain.jooq.tables.User;
import me.myblog.framework.domain.jooq.tables.UserRole;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Myblog extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>myblog</code>
     */
    public static final Myblog MYBLOG = new Myblog();

    /**
     * 文章表
     */
    public final Article ARTICLE = Article.ARTICLE;

    /**
     * 文章标签关联表
     */
    public final ArticleTag ARTICLE_TAG = ArticleTag.ARTICLE_TAG;

    /**
     * 分类表
     */
    public final Category CATEGORY = Category.CATEGORY;

    /**
     * 评论表
     */
    public final Comment COMMENT = Comment.COMMENT;

    /**
     * 友链
     */
    public final Link LINK = Link.LINK;

    /**
     * 菜单权限表
     */
    public final Menu MENU = Menu.MENU;

    /**
     * 角色信息表
     */
    public final Role ROLE = Role.ROLE;

    /**
     * 标签
     */
    public final Tag TAG = Tag.TAG;

    /**
     * 用户表
     */
    public final User USER = User.USER;

    /**
     * 用户和角色关联表
     */
    public final UserRole USER_ROLE = UserRole.USER_ROLE;

    /**
     * No further instances allowed
     */
    private Myblog() {
        super("myblog", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Article.ARTICLE,
            ArticleTag.ARTICLE_TAG,
            Category.CATEGORY,
            Comment.COMMENT,
            Link.LINK,
            Menu.MENU,
            Role.ROLE,
            Tag.TAG,
            User.USER,
            UserRole.USER_ROLE
        );
    }
}
