/*
 * This file is generated by jOOQ.
 */
package me.myblog.framework.domain.jooq;


import me.myblog.framework.domain.jooq.tables.Article;
import me.myblog.framework.domain.jooq.tables.ArticleTag;
import me.myblog.framework.domain.jooq.tables.Category;
import me.myblog.framework.domain.jooq.tables.Comment;
import me.myblog.framework.domain.jooq.tables.Link;
import me.myblog.framework.domain.jooq.tables.Menu;
import me.myblog.framework.domain.jooq.tables.Role;
import me.myblog.framework.domain.jooq.tables.Tag;
import me.myblog.framework.domain.jooq.tables.User;
import me.myblog.framework.domain.jooq.tables.UserRole;


/**
 * Convenience access to all tables in myblog.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * 文章表
     */
    public static final Article ARTICLE = Article.ARTICLE;

    /**
     * 文章标签关联表
     */
    public static final ArticleTag ARTICLE_TAG = ArticleTag.ARTICLE_TAG;

    /**
     * 分类表
     */
    public static final Category CATEGORY = Category.CATEGORY;

    /**
     * 评论表
     */
    public static final Comment COMMENT = Comment.COMMENT;

    /**
     * 友链
     */
    public static final Link LINK = Link.LINK;

    /**
     * 菜单权限表
     */
    public static final Menu MENU = Menu.MENU;

    /**
     * 角色信息表
     */
    public static final Role ROLE = Role.ROLE;

    /**
     * 标签
     */
    public static final Tag TAG = Tag.TAG;

    /**
     * 用户表
     */
    public static final User USER = User.USER;

    /**
     * 用户和角色关联表
     */
    public static final UserRole USER_ROLE = UserRole.USER_ROLE;
}
