/*
 * This file is generated by jOOQ.
 */
package me.myblog.framework.domain.jooq.tables.interfaces;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * 文章表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public interface IArticle extends Serializable {

    /**
     * Setter for <code>myblog.article.id</code>.
     */
    public void setId(Long value);

    /**
     * Getter for <code>myblog.article.id</code>.
     */
    public Long getId();

    /**
     * Setter for <code>myblog.article.title</code>. 标题
     */
    public void setTitle(String value);

    /**
     * Getter for <code>myblog.article.title</code>. 标题
     */
    public String getTitle();

    /**
     * Setter for <code>myblog.article.content</code>. 文章内容
     */
    public void setContent(String value);

    /**
     * Getter for <code>myblog.article.content</code>. 文章内容
     */
    public String getContent();

    /**
     * Setter for <code>myblog.article.summary</code>. 文章摘要
     */
    public void setSummary(String value);

    /**
     * Getter for <code>myblog.article.summary</code>. 文章摘要
     */
    public String getSummary();

    /**
     * Setter for <code>myblog.article.category_id</code>. 所属分类id
     */
    public void setCategoryId(Long value);

    /**
     * Getter for <code>myblog.article.category_id</code>. 所属分类id
     */
    public Long getCategoryId();

    /**
     * Setter for <code>myblog.article.thumbnail</code>. 缩略图
     */
    public void setThumbnail(String value);

    /**
     * Getter for <code>myblog.article.thumbnail</code>. 缩略图
     */
    public String getThumbnail();

    /**
     * Setter for <code>myblog.article.is_top</code>. 是否置顶（0否，1是）
     */
    public void setIsTop(String value);

    /**
     * Getter for <code>myblog.article.is_top</code>. 是否置顶（0否，1是）
     */
    public String getIsTop();

    /**
     * Setter for <code>myblog.article.status</code>. 状态（0已发布，1草稿）
     */
    public void setStatus(String value);

    /**
     * Getter for <code>myblog.article.status</code>. 状态（0已发布，1草稿）
     */
    public String getStatus();

    /**
     * Setter for <code>myblog.article.view_count</code>. 访问量
     */
    public void setViewCount(Long value);

    /**
     * Getter for <code>myblog.article.view_count</code>. 访问量
     */
    public Long getViewCount();

    /**
     * Setter for <code>myblog.article.is_comment</code>. 是否允许评论（1是，0否）
     */
    public void setIsComment(String value);

    /**
     * Getter for <code>myblog.article.is_comment</code>. 是否允许评论（1是，0否）
     */
    public String getIsComment();

    /**
     * Setter for <code>myblog.article.create_by</code>.
     */
    public void setCreateBy(Long value);

    /**
     * Getter for <code>myblog.article.create_by</code>.
     */
    public Long getCreateBy();

    /**
     * Setter for <code>myblog.article.create_time</code>.
     */
    public void setCreateTime(LocalDateTime value);

    /**
     * Getter for <code>myblog.article.create_time</code>.
     */
    public LocalDateTime getCreateTime();

    /**
     * Setter for <code>myblog.article.update_by</code>.
     */
    public void setUpdateBy(Long value);

    /**
     * Getter for <code>myblog.article.update_by</code>.
     */
    public Long getUpdateBy();

    /**
     * Setter for <code>myblog.article.update_time</code>.
     */
    public void setUpdateTime(LocalDateTime value);

    /**
     * Getter for <code>myblog.article.update_time</code>.
     */
    public LocalDateTime getUpdateTime();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common
     * interface IArticle
     */
    public void from(IArticle from);

    /**
     * Copy data into another generated Record/POJO implementing the common
     * interface IArticle
     */
    public <E extends IArticle> E into(E into);
}
