/*
 * This file is generated by jOOQ.
 */
package me.myblog.framework.domain.jooq.tables.interfaces;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * 分类表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public interface ICategory extends Serializable {

    /**
     * Setter for <code>myblog.category.id</code>.
     */
    public void setId(Long value);

    /**
     * Getter for <code>myblog.category.id</code>.
     */
    public Long getId();

    /**
     * Setter for <code>myblog.category.name</code>. 分类名
     */
    public void setName(String value);

    /**
     * Getter for <code>myblog.category.name</code>. 分类名
     */
    public String getName();

    /**
     * Setter for <code>myblog.category.pid</code>. 父分类id，如果没有父分类为-1
     */
    public void setPid(Long value);

    /**
     * Getter for <code>myblog.category.pid</code>. 父分类id，如果没有父分类为-1
     */
    public Long getPid();

    /**
     * Setter for <code>myblog.category.description</code>. 描述
     */
    public void setDescription(String value);

    /**
     * Getter for <code>myblog.category.description</code>. 描述
     */
    public String getDescription();

    /**
     * Setter for <code>myblog.category.status</code>. 状态（0正常，1禁用）
     */
    public void setStatus(String value);

    /**
     * Getter for <code>myblog.category.status</code>. 状态（0正常，1禁用）
     */
    public String getStatus();

    /**
     * Setter for <code>myblog.category.create_by</code>.
     */
    public void setCreateBy(Long value);

    /**
     * Getter for <code>myblog.category.create_by</code>.
     */
    public Long getCreateBy();

    /**
     * Setter for <code>myblog.category.create_time</code>.
     */
    public void setCreateTime(LocalDateTime value);

    /**
     * Getter for <code>myblog.category.create_time</code>.
     */
    public LocalDateTime getCreateTime();

    /**
     * Setter for <code>myblog.category.update_by</code>.
     */
    public void setUpdateBy(Long value);

    /**
     * Getter for <code>myblog.category.update_by</code>.
     */
    public Long getUpdateBy();

    /**
     * Setter for <code>myblog.category.update_time</code>.
     */
    public void setUpdateTime(LocalDateTime value);

    /**
     * Getter for <code>myblog.category.update_time</code>.
     */
    public LocalDateTime getUpdateTime();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common
     * interface ICategory
     */
    public void from(ICategory from);

    /**
     * Copy data into another generated Record/POJO implementing the common
     * interface ICategory
     */
    public <E extends ICategory> E into(E into);
}
