/*
 * This file is generated by jOOQ.
 */
package me.myblog.framework.domain.jooq.tables.interfaces;


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.validation.constraints.Size;

import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * 分类表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
@Entity
@Table(
    name = "category",
    schema = "myblog"
)
public interface ICategory extends Serializable {

    /**
     * Getter for <code>myblog.category.id</code>.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    public Long getId();

    /**
     * Getter for <code>myblog.category.name</code>. 分类名
     */
    @Column(name = "name", length = 128)
    @Size(max = 128)
    public String getName();

    /**
     * Getter for <code>myblog.category.pid</code>. 父分类id，如果没有父分类为-1
     */
    @Column(name = "pid")
    public Long getPid();

    /**
     * Getter for <code>myblog.category.description</code>. 描述
     */
    @Column(name = "description", length = 512)
    @Size(max = 512)
    public String getDescription();

    /**
     * Getter for <code>myblog.category.status</code>. 状态（0正常，1禁用）
     */
    @Column(name = "status", length = 1)
    @Size(max = 1)
    public String getStatus();

    /**
     * Getter for <code>myblog.category.create_by</code>.
     */
    @Column(name = "create_by")
    public Long getCreateBy();

    /**
     * Getter for <code>myblog.category.create_time</code>.
     */
    @Column(name = "create_time")
    public LocalDateTime getCreateTime();

    /**
     * Getter for <code>myblog.category.update_by</code>.
     */
    @Column(name = "update_by")
    public Long getUpdateBy();

    /**
     * Getter for <code>myblog.category.update_time</code>.
     */
    @Column(name = "update_time")
    public LocalDateTime getUpdateTime();
}
