/*
 * This file is generated by jOOQ.
 */
package me.myblog.framework.domain.jooq.tables.interfaces;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * 评论表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public interface IComment extends Serializable {

    /**
     * Setter for <code>myblog.comment.id</code>.
     */
    public void setId(Long value);

    /**
     * Getter for <code>myblog.comment.id</code>.
     */
    public Long getId();

    /**
     * Setter for <code>myblog.comment.type</code>. 评论类型（0代表文章评论，1代表友链评论）
     */
    public void setType(String value);

    /**
     * Getter for <code>myblog.comment.type</code>. 评论类型（0代表文章评论，1代表友链评论）
     */
    public String getType();

    /**
     * Setter for <code>myblog.comment.article_id</code>. 文章id
     */
    public void setArticleId(Long value);

    /**
     * Getter for <code>myblog.comment.article_id</code>. 文章id
     */
    public Long getArticleId();

    /**
     * Setter for <code>myblog.comment.root_id</code>. 根评论id
     */
    public void setRootId(Long value);

    /**
     * Getter for <code>myblog.comment.root_id</code>. 根评论id
     */
    public Long getRootId();

    /**
     * Setter for <code>myblog.comment.content</code>. 评论内容
     */
    public void setContent(String value);

    /**
     * Getter for <code>myblog.comment.content</code>. 评论内容
     */
    public String getContent();

    /**
     * Setter for <code>myblog.comment.to_comment_user_id</code>.
     * 所回复的目标评论的userid
     */
    public void setToCommentUserId(Long value);

    /**
     * Getter for <code>myblog.comment.to_comment_user_id</code>.
     * 所回复的目标评论的userid
     */
    public Long getToCommentUserId();

    /**
     * Setter for <code>myblog.comment.to_comment_id</code>. 回复目标评论id
     */
    public void setToCommentId(Long value);

    /**
     * Getter for <code>myblog.comment.to_comment_id</code>. 回复目标评论id
     */
    public Long getToCommentId();

    /**
     * Setter for <code>myblog.comment.create_by</code>.
     */
    public void setCreateBy(Long value);

    /**
     * Getter for <code>myblog.comment.create_by</code>.
     */
    public Long getCreateBy();

    /**
     * Setter for <code>myblog.comment.create_time</code>.
     */
    public void setCreateTime(LocalDateTime value);

    /**
     * Getter for <code>myblog.comment.create_time</code>.
     */
    public LocalDateTime getCreateTime();

    /**
     * Setter for <code>myblog.comment.update_by</code>.
     */
    public void setUpdateBy(Long value);

    /**
     * Getter for <code>myblog.comment.update_by</code>.
     */
    public Long getUpdateBy();

    /**
     * Setter for <code>myblog.comment.update_time</code>.
     */
    public void setUpdateTime(LocalDateTime value);

    /**
     * Getter for <code>myblog.comment.update_time</code>.
     */
    public LocalDateTime getUpdateTime();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common
     * interface IComment
     */
    public void from(IComment from);

    /**
     * Copy data into another generated Record/POJO implementing the common
     * interface IComment
     */
    public <E extends IComment> E into(E into);
}
