/*
 * This file is generated by jOOQ.
 */
package me.myblog.framework.domain.jooq.tables.interfaces;


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.validation.constraints.Size;

import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * 友链
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
@Entity
@Table(
    name = "link",
    schema = "myblog"
)
public interface ILink extends Serializable {

    /**
     * Getter for <code>myblog.link.id</code>.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    public Long getId();

    /**
     * Getter for <code>myblog.link.name</code>.
     */
    @Column(name = "name", length = 256)
    @Size(max = 256)
    public String getName();

    /**
     * Getter for <code>myblog.link.logo</code>.
     */
    @Column(name = "logo", length = 256)
    @Size(max = 256)
    public String getLogo();

    /**
     * Getter for <code>myblog.link.description</code>.
     */
    @Column(name = "description", length = 512)
    @Size(max = 512)
    public String getDescription();

    /**
     * Getter for <code>myblog.link.address</code>. 网站地址
     */
    @Column(name = "address", length = 128)
    @Size(max = 128)
    public String getAddress();

    /**
     * Getter for <code>myblog.link.status</code>. 审核状态
     * (0代表审核通过，1代表审核未通过，2代表未审核)
     */
    @Column(name = "status", length = 1)
    @Size(max = 1)
    public String getStatus();

    /**
     * Getter for <code>myblog.link.create_by</code>.
     */
    @Column(name = "create_by")
    public Long getCreateBy();

    /**
     * Getter for <code>myblog.link.create_time</code>.
     */
    @Column(name = "create_time")
    public LocalDateTime getCreateTime();

    /**
     * Getter for <code>myblog.link.update_by</code>.
     */
    @Column(name = "update_by")
    public Long getUpdateBy();

    /**
     * Getter for <code>myblog.link.update_time</code>.
     */
    @Column(name = "update_time")
    public LocalDateTime getUpdateTime();
}
