/*
 * This file is generated by jOOQ.
 */
package me.myblog.framework.domain.jooq.tables.interfaces;


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * 角色信息表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
@Entity
@Table(
    name = "role",
    schema = "myblog"
)
public interface IRole extends Serializable {

    /**
     * Getter for <code>myblog.role.id</code>. 角色ID
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    public Long getId();

    /**
     * Getter for <code>myblog.role.role_name</code>. 角色名称
     */
    @Column(name = "role_name", nullable = false, length = 30)
    @NotNull
    @Size(max = 30)
    public String getRoleName();

    /**
     * Getter for <code>myblog.role.role_key</code>. 角色权限字符串
     */
    @Column(name = "role_key", nullable = false, length = 100)
    @NotNull
    @Size(max = 100)
    public String getRoleKey();

    /**
     * Getter for <code>myblog.role.role_sort</code>. 显示顺序
     */
    @Column(name = "role_sort", nullable = false)
    @NotNull
    public Integer getRoleSort();

    /**
     * Getter for <code>myblog.role.status</code>. 角色状态（0正常，1停用）
     */
    @Column(name = "status", nullable = false, length = 1)
    @NotNull
    @Size(max = 1)
    public String getStatus();

    /**
     * Getter for <code>myblog.role.create_by</code>. 创建者
     */
    @Column(name = "create_by")
    public Long getCreateBy();

    /**
     * Getter for <code>myblog.role.create_time</code>. 创建时间
     */
    @Column(name = "create_time")
    public LocalDateTime getCreateTime();

    /**
     * Getter for <code>myblog.role.update_by</code>. 更新者
     */
    @Column(name = "update_by")
    public Long getUpdateBy();

    /**
     * Getter for <code>myblog.role.update_time</code>. 更新时间
     */
    @Column(name = "update_time")
    public LocalDateTime getUpdateTime();

    /**
     * Getter for <code>myblog.role.remark</code>. 备注
     */
    @Column(name = "remark", length = 500)
    @Size(max = 500)
    public String getRemark();
}
