/*
 * This file is generated by jOOQ.
 */
package me.myblog.framework.domain.jooq.tables.interfaces;


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.validation.constraints.Size;

import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * 标签
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
@Entity
@Table(
    name = "tag",
    schema = "myblog"
)
public interface ITag extends Serializable {

    /**
     * Getter for <code>myblog.tag.id</code>.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    public Long getId();

    /**
     * Getter for <code>myblog.tag.name</code>. 标签名
     */
    @Column(name = "name", length = 128)
    @Size(max = 128)
    public String getName();

    /**
     * Getter for <code>myblog.tag.create_by</code>.
     */
    @Column(name = "create_by")
    public Long getCreateBy();

    /**
     * Getter for <code>myblog.tag.create_time</code>.
     */
    @Column(name = "create_time")
    public LocalDateTime getCreateTime();

    /**
     * Getter for <code>myblog.tag.update_by</code>.
     */
    @Column(name = "update_by")
    public Long getUpdateBy();

    /**
     * Getter for <code>myblog.tag.update_time</code>.
     */
    @Column(name = "update_time")
    public LocalDateTime getUpdateTime();

    /**
     * Getter for <code>myblog.tag.remark</code>. 备注
     */
    @Column(name = "remark", length = 500)
    @Size(max = 500)
    public String getRemark();
}
