/*
 * This file is generated by jOOQ.
 */
package me.myblog.framework.domain.jooq.tables.interfaces;


import java.io.Serializable;


/**
 * 用户和角色关联表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public interface IUserRole extends Serializable {

    /**
     * Setter for <code>myblog.user_role.user_id</code>. 用户ID
     */
    public void setUserId(Long value);

    /**
     * Getter for <code>myblog.user_role.user_id</code>. 用户ID
     */
    public Long getUserId();

    /**
     * Setter for <code>myblog.user_role.role_id</code>. 角色ID
     */
    public void setRoleId(Long value);

    /**
     * Getter for <code>myblog.user_role.role_id</code>. 角色ID
     */
    public Long getRoleId();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common
     * interface IUserRole
     */
    public void from(IUserRole from);

    /**
     * Copy data into another generated Record/POJO implementing the common
     * interface IUserRole
     */
    public <E extends IUserRole> E into(E into);
}
