/*
 * This file is generated by jOOQ.
 */
package me.myblog.framework.domain.jooq.tables.interfaces;


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Table;
import jakarta.validation.constraints.NotNull;

import java.io.Serializable;


/**
 * 用户和角色关联表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
@Entity
@Table(
    name = "user_role",
    schema = "myblog"
)
public interface IUserRole extends Serializable {

    /**
     * Getter for <code>myblog.user_role.user_id</code>. 用户ID
     */
    @Column(name = "user_id", nullable = false)
    @NotNull
    public Long getUserId();

    /**
     * Getter for <code>myblog.user_role.role_id</code>. 角色ID
     */
    @Column(name = "role_id", nullable = false)
    @NotNull
    public Long getRoleId();
}
