/*
 * This file is generated by jOOQ.
 */
package me.myblog.framework.domain.jooq.tables.daos;


import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

import me.myblog.framework.domain.jooq.tables.Menu;
import me.myblog.framework.domain.jooq.tables.records.MenuRecord;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * 菜单权限表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
@Repository
public class MenuDao extends DAOImpl<MenuRecord, me.myblog.framework.domain.jooq.tables.pojos.Menu, Long> {

    /**
     * Create a new MenuDao without any configuration
     */
    public MenuDao() {
        super(Menu.MENU, me.myblog.framework.domain.jooq.tables.pojos.Menu.class);
    }

    /**
     * Create a new MenuDao with an attached configuration
     */
    @Autowired
    public MenuDao(Configuration configuration) {
        super(Menu.MENU, me.myblog.framework.domain.jooq.tables.pojos.Menu.class, configuration);
    }

    @Override
    public Long getId(me.myblog.framework.domain.jooq.tables.pojos.Menu object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<me.myblog.framework.domain.jooq.tables.pojos.Menu> fetchRangeOfId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(Menu.MENU.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<me.myblog.framework.domain.jooq.tables.pojos.Menu> fetchById(Long... values) {
        return fetch(Menu.MENU.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public me.myblog.framework.domain.jooq.tables.pojos.Menu fetchOneById(Long value) {
        return fetchOne(Menu.MENU.ID, value);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public Optional<me.myblog.framework.domain.jooq.tables.pojos.Menu> fetchOptionalById(Long value) {
        return fetchOptional(Menu.MENU.ID, value);
    }

    /**
     * Fetch records that have <code>menu_name BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<me.myblog.framework.domain.jooq.tables.pojos.Menu> fetchRangeOfMenuName(String lowerInclusive, String upperInclusive) {
        return fetchRange(Menu.MENU.MENU_NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>menu_name IN (values)</code>
     */
    public List<me.myblog.framework.domain.jooq.tables.pojos.Menu> fetchByMenuName(String... values) {
        return fetch(Menu.MENU.MENU_NAME, values);
    }

    /**
     * Fetch records that have <code>parent_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<me.myblog.framework.domain.jooq.tables.pojos.Menu> fetchRangeOfParentId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(Menu.MENU.PARENT_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>parent_id IN (values)</code>
     */
    public List<me.myblog.framework.domain.jooq.tables.pojos.Menu> fetchByParentId(Long... values) {
        return fetch(Menu.MENU.PARENT_ID, values);
    }

    /**
     * Fetch records that have <code>order_num BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<me.myblog.framework.domain.jooq.tables.pojos.Menu> fetchRangeOfOrderNum(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(Menu.MENU.ORDER_NUM, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>order_num IN (values)</code>
     */
    public List<me.myblog.framework.domain.jooq.tables.pojos.Menu> fetchByOrderNum(Integer... values) {
        return fetch(Menu.MENU.ORDER_NUM, values);
    }

    /**
     * Fetch records that have <code>path BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<me.myblog.framework.domain.jooq.tables.pojos.Menu> fetchRangeOfPath(String lowerInclusive, String upperInclusive) {
        return fetchRange(Menu.MENU.PATH, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>path IN (values)</code>
     */
    public List<me.myblog.framework.domain.jooq.tables.pojos.Menu> fetchByPath(String... values) {
        return fetch(Menu.MENU.PATH, values);
    }

    /**
     * Fetch records that have <code>component BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<me.myblog.framework.domain.jooq.tables.pojos.Menu> fetchRangeOfComponent(String lowerInclusive, String upperInclusive) {
        return fetchRange(Menu.MENU.COMPONENT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>component IN (values)</code>
     */
    public List<me.myblog.framework.domain.jooq.tables.pojos.Menu> fetchByComponent(String... values) {
        return fetch(Menu.MENU.COMPONENT, values);
    }

    /**
     * Fetch records that have <code>is_frame BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<me.myblog.framework.domain.jooq.tables.pojos.Menu> fetchRangeOfIsFrame(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(Menu.MENU.IS_FRAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>is_frame IN (values)</code>
     */
    public List<me.myblog.framework.domain.jooq.tables.pojos.Menu> fetchByIsFrame(Integer... values) {
        return fetch(Menu.MENU.IS_FRAME, values);
    }

    /**
     * Fetch records that have <code>menu_type BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<me.myblog.framework.domain.jooq.tables.pojos.Menu> fetchRangeOfMenuType(String lowerInclusive, String upperInclusive) {
        return fetchRange(Menu.MENU.MENU_TYPE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>menu_type IN (values)</code>
     */
    public List<me.myblog.framework.domain.jooq.tables.pojos.Menu> fetchByMenuType(String... values) {
        return fetch(Menu.MENU.MENU_TYPE, values);
    }

    /**
     * Fetch records that have <code>visible BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<me.myblog.framework.domain.jooq.tables.pojos.Menu> fetchRangeOfVisible(String lowerInclusive, String upperInclusive) {
        return fetchRange(Menu.MENU.VISIBLE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>visible IN (values)</code>
     */
    public List<me.myblog.framework.domain.jooq.tables.pojos.Menu> fetchByVisible(String... values) {
        return fetch(Menu.MENU.VISIBLE, values);
    }

    /**
     * Fetch records that have <code>status BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<me.myblog.framework.domain.jooq.tables.pojos.Menu> fetchRangeOfStatus(String lowerInclusive, String upperInclusive) {
        return fetchRange(Menu.MENU.STATUS, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>status IN (values)</code>
     */
    public List<me.myblog.framework.domain.jooq.tables.pojos.Menu> fetchByStatus(String... values) {
        return fetch(Menu.MENU.STATUS, values);
    }

    /**
     * Fetch records that have <code>perms BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<me.myblog.framework.domain.jooq.tables.pojos.Menu> fetchRangeOfPerms(String lowerInclusive, String upperInclusive) {
        return fetchRange(Menu.MENU.PERMS, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>perms IN (values)</code>
     */
    public List<me.myblog.framework.domain.jooq.tables.pojos.Menu> fetchByPerms(String... values) {
        return fetch(Menu.MENU.PERMS, values);
    }

    /**
     * Fetch records that have <code>icon BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<me.myblog.framework.domain.jooq.tables.pojos.Menu> fetchRangeOfIcon(String lowerInclusive, String upperInclusive) {
        return fetchRange(Menu.MENU.ICON, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>icon IN (values)</code>
     */
    public List<me.myblog.framework.domain.jooq.tables.pojos.Menu> fetchByIcon(String... values) {
        return fetch(Menu.MENU.ICON, values);
    }

    /**
     * Fetch records that have <code>create_by BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<me.myblog.framework.domain.jooq.tables.pojos.Menu> fetchRangeOfCreateBy(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(Menu.MENU.CREATE_BY, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>create_by IN (values)</code>
     */
    public List<me.myblog.framework.domain.jooq.tables.pojos.Menu> fetchByCreateBy(Long... values) {
        return fetch(Menu.MENU.CREATE_BY, values);
    }

    /**
     * Fetch records that have <code>create_time BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<me.myblog.framework.domain.jooq.tables.pojos.Menu> fetchRangeOfCreateTime(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(Menu.MENU.CREATE_TIME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>create_time IN (values)</code>
     */
    public List<me.myblog.framework.domain.jooq.tables.pojos.Menu> fetchByCreateTime(LocalDateTime... values) {
        return fetch(Menu.MENU.CREATE_TIME, values);
    }

    /**
     * Fetch records that have <code>update_by BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<me.myblog.framework.domain.jooq.tables.pojos.Menu> fetchRangeOfUpdateBy(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(Menu.MENU.UPDATE_BY, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>update_by IN (values)</code>
     */
    public List<me.myblog.framework.domain.jooq.tables.pojos.Menu> fetchByUpdateBy(Long... values) {
        return fetch(Menu.MENU.UPDATE_BY, values);
    }

    /**
     * Fetch records that have <code>update_time BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<me.myblog.framework.domain.jooq.tables.pojos.Menu> fetchRangeOfUpdateTime(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(Menu.MENU.UPDATE_TIME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>update_time IN (values)</code>
     */
    public List<me.myblog.framework.domain.jooq.tables.pojos.Menu> fetchByUpdateTime(LocalDateTime... values) {
        return fetch(Menu.MENU.UPDATE_TIME, values);
    }

    /**
     * Fetch records that have <code>remark BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<me.myblog.framework.domain.jooq.tables.pojos.Menu> fetchRangeOfRemark(String lowerInclusive, String upperInclusive) {
        return fetchRange(Menu.MENU.REMARK, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>remark IN (values)</code>
     */
    public List<me.myblog.framework.domain.jooq.tables.pojos.Menu> fetchByRemark(String... values) {
        return fetch(Menu.MENU.REMARK, values);
    }
}
